version: '3.7'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node
    restart: always
    ports:
      - 3030:3030
    volumes:
      - ./:/usr/src/app
    networks:
      - chatbot_network
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGODB_DATABASE: test
    ports:
      - 27017:27017
    networks:
      - chatbot_network

  mongo-express:
    image: mongo-express
    container_name: mongo-express-app
    restart: always
    ports:
      - 8081:8081
    volumes:
      - ./data/db/mongoexpress:/data/db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    networks:
      - chatbot_network

volumes:
  mongo:
    driver: local
  mongo-express:
    driver: local
  node:
    driver: local

networks:
  chatbot_network:
    driver: bridge