version: '3.7'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node
    restart: always
    ports:
      - 3030:3030
    volumes:
      - ./:/usr/src/app
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./data/db/mongo:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    volumes:
      - ./data/db/mongoexpress:/data/db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

volumes:
  mongo:
    driver: local
  mongo-express:
    driver: local
  node:
    driver: local
